
name: ASCII Workflow

on:
  - push

jobs: 
    first_job: 
        name: Saadia 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Execute Shell Script
              run: ./ascii-script.sh